#
# developed by Sergey Markelov (11/10/2013)
#

PROG       := terminal-binary-clock
LIBS        = -lncurses
SOURCES     = $(wildcard arch/*.c)
CTAGS_FILE := ../etc/emulator.tags
CTAGS_DIR  := ../emulator

all: $(PROG)

include ../include/Makefile.include
